# Generated by Django 5.1.1 on 2024-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
    ]
